const sampleProfiles = [
  {
    username: "torvalds",
    avatar: "https://avatars.githubusercontent.com/u/1024025",
    bio: "Creator of Linux and Git",
    publicRepos: 7,
    followers: 230000,
    following: 0,
    totalStars: 185000,
    totalForks: 45000,
    topLanguages: ["C", "Shell", "C++"],
    topRepos: [
      { name: "linux", stars: 180000, language: "C", url: "https://github.com/torvalds/linux" },
      { name: "subsurface-for-dirk", stars: 2000, language: "C++", url: "https://github.com/torvalds/subsurface-for-dirk" },
    ],
    profileUrl: "https://github.com/torvalds",
    contributionScore: 100,
    tags: ["legend", "systems", "open-source"],
    notes: "Creator of Linux kernel and Git version control.",
  },
  {
    username: "gaearon",
    avatar: "https://avatars.githubusercontent.com/u/810438",
    bio: "Working on @reactjs. Co-author of Redux and Create React App.",
    publicRepos: 270,
    followers: 78000,
    following: 15,
    totalStars: 95000,
    totalForks: 12000,
    topLanguages: ["JavaScript", "TypeScript", "CSS"],
    topRepos: [
      { name: "react-hot-loader", stars: 12500, language: "JavaScript", url: "https://github.com/gaearon/react-hot-loader" },
      { name: "overreacted.io", stars: 5200, language: "JavaScript", url: "https://github.com/gaearon/overreacted.io" },
    ],
    profileUrl: "https://github.com/gaearon",
    contributionScore: 92,
    tags: ["react", "frontend", "open-source"],
    notes: "Core React team member, Redux co-author.",
  },
  {
    username: "sindresorhus",
    avatar: "https://avatars.githubusercontent.com/u/170270",
    bio: "Full-Time Open-Sourcerer. Focuses on Swift & Node.js. Creates macOS apps.",
    publicRepos: 1200,
    followers: 56000,
    following: 25,
    totalStars: 320000,
    totalForks: 28000,
    topLanguages: ["JavaScript", "Swift", "TypeScript"],
    topRepos: [
      { name: "awesome", stars: 330000, language: "JavaScript", url: "https://github.com/sindresorhus/awesome" },
      { name: "pure", stars: 10000, language: "Shell", url: "https://github.com/sindresorhus/pure" },
    ],
    profileUrl: "https://github.com/sindresorhus",
    contributionScore: 98,
    tags: ["prolific", "nodejs", "swift"],
    notes: "One of the most prolific open source developers on GitHub.",
  },
  {
    username: "tj",
    avatar: "https://avatars.githubusercontent.com/u/25254",
    bio: "Founder of Apex Software.",
    publicRepos: 320,
    followers: 38000,
    following: 0,
    totalStars: 85000,
    totalForks: 7500,
    topLanguages: ["Go", "JavaScript", "C"],
    topRepos: [
      { name: "express", stars: 64000, language: "JavaScript", url: "https://github.com/expressjs/express" },
      { name: "koajs", stars: 35000, language: "JavaScript", url: "https://github.com/koajs/koa" },
    ],
    profileUrl: "https://github.com/tj",
    contributionScore: 90,
    tags: ["nodejs", "frameworks", "pioneer"],
    notes: "Created Express.js, Koa, and many influential Node.js tools.",
  },
  {
    username: "yyx990803",
    avatar: "https://avatars.githubusercontent.com/u/499550",
    bio: "Independent developer. Creator of Vue.js and Vite.",
    publicRepos: 180,
    followers: 92000,
    following: 10,
    totalStars: 210000,
    totalForks: 35000,
    topLanguages: ["TypeScript", "JavaScript", "Vue"],
    topRepos: [
      { name: "vue", stars: 208000, language: "TypeScript", url: "https://github.com/vuejs/core" },
      { name: "vite", stars: 67000, language: "TypeScript", url: "https://github.com/vitejs/vite" },
    ],
    profileUrl: "https://github.com/yyx990803",
    contributionScore: 96,
    tags: ["vue", "frontend", "frameworks"],
    notes: "Creator of Vue.js, one of the most popular frontend frameworks.",
  },
  {
    username: "fabpot",
    avatar: "https://avatars.githubusercontent.com/u/47313",
    bio: "CEO of Symfony SAS. Creator of Symfony PHP framework.",
    publicRepos: 150,
    followers: 8500,
    following: 0,
    totalStars: 29000,
    totalForks: 9500,
    topLanguages: ["PHP", "Shell"],
    topRepos: [
      { name: "symfony", stars: 29000, language: "PHP", url: "https://github.com/symfony/symfony" },
    ],
    profileUrl: "https://github.com/fabpot",
    contributionScore: 72,
    tags: ["php", "symfony", "backend"],
    notes: "Leading figure in the PHP ecosystem.",
  },
  {
    username: "karpathy",
    avatar: "https://avatars.githubusercontent.com/u/241138",
    bio: "I like to train deep neural nets on large datasets.",
    publicRepos: 65,
    followers: 110000,
    following: 0,
    totalStars: 98000,
    totalForks: 18000,
    topLanguages: ["Python", "Jupyter Notebook", "C++"],
    topRepos: [
      { name: "nanoGPT", stars: 37000, language: "Python", url: "https://github.com/karpathy/nanoGPT" },
      { name: "minGPT", stars: 16000, language: "Python", url: "https://github.com/karpathy/minGPT" },
    ],
    profileUrl: "https://github.com/karpathy",
    contributionScore: 94,
    tags: ["ai", "deep-learning", "education"],
    notes: "Former Director of AI at Tesla, prominent AI educator.",
  },
  {
    username: "mitchellh",
    avatar: "https://avatars.githubusercontent.com/u/1299",
    bio: "Founder of Ghostty and Ghostty Corp. Creator of Vagrant, Packer, Consul, Vault, Terraform.",
    publicRepos: 200,
    followers: 24000,
    following: 5,
    totalStars: 45000,
    totalForks: 5500,
    topLanguages: ["Go", "Ruby", "HCL"],
    topRepos: [
      { name: "ghostty", stars: 17000, language: "Zig", url: "https://github.com/ghostty-org/ghostty" },
      { name: "copyist", stars: 300, language: "Go", url: "https://github.com/mitchellh/copyist" },
    ],
    profileUrl: "https://github.com/mitchellh",
    contributionScore: 88,
    tags: ["devops", "infrastructure", "hashicorp"],
    notes: "Founded HashiCorp, created many essential DevOps tools.",
  },
  {
    username: "antirez",
    avatar: "https://avatars.githubusercontent.com/u/65666",
    bio: "Creator of Redis. Working at Valkey.",
    publicRepos: 120,
    followers: 42000,
    following: 0,
    totalStars: 66000,
    totalForks: 23000,
    topLanguages: ["C", "Tcl", "Lua"],
    topRepos: [
      { name: "redis", stars: 66000, language: "C", url: "https://github.com/redis/redis" },
      { name: "linenoise", stars: 5000, language: "C", url: "https://github.com/antirez/linenoise" },
    ],
    profileUrl: "https://github.com/antirez",
    contributionScore: 91,
    tags: ["redis", "databases", "c"],
    notes: "Creator of Redis, one of the most widely used databases.",
  },
];

module.exports = { data: sampleProfiles };