const indianProfiles = [
  {
    username: "raghuvirsingh",
    avatar: "https://avatars.githubusercontent.com/u/1234567",
    bio: "Full-stack developer from Mumbai. React & Node.js enthusiast.",
    publicRepos: 45,
    followers: 320,
    following: 15,
    totalStars: 850,
    totalForks: 210,
    topLanguages: ["JavaScript", "TypeScript", "Python"],
    topRepos: [
      { name: "react-dashboard", stars: 450, language: "TypeScript", url: "https://github.com/raghuvirsingh/react-dashboard" },
      { name: "node-api-starter", stars: 280, language: "JavaScript", url: "https://github.com/raghuvirsingh/node-api-starter" },
    ],
    profileUrl: "https://github.com/raghuvirsingh",
    contributionScore: 42,
    tags: ["fullstack", "react", "nodejs"],
    notes: "Active contributor to React ecosystem.",
  },
  {
    username: "priyankav",
    avatar: "https://avatars.githubusercontent.com/u/2345678",
    bio: "ML Engineer at Bangalore. Working on NLP and computer vision.",
    publicRepos: 38,
    followers: 580,
    following: 22,
    totalStars: 1200,
    totalForks: 340,
    topLanguages: ["Python", "Jupyter Notebook", "C++"],
    topRepos: [
      { name: "text-classifier", stars: 680, language: "Python", url: "https://github.com/priyankav/text-classifier" },
      { name: "cv-toolkit", stars: 420, language: "Python", url: "https://github.com/priyankav/cv-toolkit" },
    ],
    profileUrl: "https://github.com/priyankav",
    contributionScore: 55,
    tags: ["machine-learning", "nlp", "python"],
    notes: "ML researcher with focus on NLP applications.",
  },
  {
    username: "arunkumar",
    avatar: "https://avatars.githubusercontent.com/u/3456789",
    bio: "DevOps engineer. Kubernetes and cloud infrastructure.",
    publicRepos: 52,
    followers: 420,
    following: 18,
    totalStars: 950,
    totalForks: 280,
    topLanguages: ["Go", "Shell", "Python"],
    topRepos: [
      { name: "k8s-deployer", stars: 520, language: "Go", url: "https://github.com/arunkumar/k8s-deployer" },
      { name: "terraform-modules", stars: 380, language: "HCL", url: "https://github.com/arunkumar/terraform-modules" },
    ],
    profileUrl: "https://github.com/arunkumar",
    contributionScore: 48,
    tags: ["devops", "kubernetes", "cloud"],
    notes: "Kubernetes expert and cloud infrastructure specialist.",
  },
  {
    username: "deepakm",
    avatar: "https://avatars.githubusercontent.com/u/4567890",
    bio: "Backend developer. Java and Spring Boot specialist.",
    publicRepos: 67,
    followers: 290,
    following: 12,
    totalStars: 680,
    totalForks: 190,
    topLanguages: ["Java", "Kotlin", "SQL"],
    topRepos: [
      { name: "spring-boot-starter", stars: 380, language: "Java", url: "https://github.com/deepakm/spring-boot-starter" },
      { name: "microservice-template", stars: 250, language: "Java", url: "https://github.com/deepakm/microservice-template" },
    ],
    profileUrl: "https://github.com/deepakm",
    contributionScore: 38,
    tags: ["java", "spring", "backend"],
    notes: "Enterprise Java developer with microservices expertise.",
  },
  {
    username: "anitas",
    avatar: "https://avatars.githubusercontent.com/u/5678901",
    bio: "Frontend developer. Vue.js and Nuxt.js enthusiast.",
    publicRepos: 41,
    followers: 380,
    following: 25,
    totalStars: 720,
    totalForks: 165,
    topLanguages: ["JavaScript", "Vue", "CSS"],
    topRepos: [
      { name: "vue-components", stars: 420, language: "Vue", url: "https://github.com/anitas/vue-components" },
      { name: "nuxt-starter", stars: 280, language: "Vue", url: "https://github.com/anitas/nuxt-starter" },
    ],
    profileUrl: "https://github.com/anitas",
    contributionScore: 45,
    tags: ["frontend", "vue", "javascript"],
    notes: "Vue.js component library creator.",
  },
  {
    username: "rahuldev",
    avatar: "https://avatars.githubusercontent.com/u/6789012",
    bio: "Mobile developer. React Native and Flutter.",
    publicRepos: 35,
    followers: 260,
    following: 20,
    totalStars: 540,
    totalForks: 140,
    topLanguages: ["Dart", "JavaScript", "Kotlin"],
    topRepos: [
      { name: "flutter-ui-kit", stars: 320, language: "Dart", url: "https://github.com/rahuldev/flutter-ui-kit" },
      { name: "react-native-boilerplate", stars: 210, language: "JavaScript", url: "https://github.com/rahuldev/react-native-boilerplate" },
    ],
    profileUrl: "https://github.com/rahuldev",
    contributionScore: 35,
    tags: ["mobile", "flutter", "react-native"],
    notes: "Cross-platform mobile app developer.",
  },
  {
    username: "kavithar",
    avatar: "https://avatars.githubusercontent.com/u/7890123",
    bio: "Data scientist. Python and R specialist.",
    publicRepos: 48,
    followers: 510,
    following: 15,
    totalStars: 890,
    totalForks: 230,
    topLanguages: ["Python", "R", "Jupyter Notebook"],
    topRepos: [
      { name: "data-analysis-toolkit", stars: 520, language: "Python", url: "https://github.com/kavithar/data-analysis-toolkit" },
      { name: "ml-pipelines", stars: 340, language: "Python", url: "https://github.com/kavithar/ml-pipelines" },
    ],
    profileUrl: "https://github.com/kavithar",
    contributionScore: 52,
    tags: ["data-science", "python", "analytics"],
    notes: "Data science tools and pipeline frameworks.",
  },
  {
    username: "vikramk",
    avatar: "https://avatars.githubusercontent.com/u/8901234",
    bio: "Security researcher. Penetration testing and ethical hacking.",
    publicRepos: 29,
    followers: 680,
    following: 8,
    totalStars: 1450,
    totalForks: 380,
    topLanguages: ["Python", "Go", "C"],
    topRepos: [
      { name: "security-scanner", stars: 850, language: "Python", url: "https://github.com/vikramk/security-scanner" },
      { name: "vuln-database", stars: 520, language: "Go", url: "https://github.com/vikramk/vuln-database" },
    ],
    profileUrl: "https://github.com/vikramk",
    contributionScore: 62,
    tags: ["security", "penetration-testing", "python"],
    notes: "Cybersecurity tools and vulnerability research.",
  },
  {
    username: "meera",
    avatar: "https://avatars.githubusercontent.com/u/9012345",
    bio: "Blockchain developer. Solidity and Web3.",
    publicRepos: 33,
    followers: 420,
    following: 18,
    totalStars: 780,
    totalForks: 195,
    topLanguages: ["Solidity", "JavaScript", "TypeScript"],
    topRepos: [
      { name: "defi-protocols", stars: 450, language: "Solidity", url: "https://github.com/meera/defi-protocols" },
      { name: "web3-tools", stars: 310, language: "TypeScript", url: "https://github.com/meera/web3-tools" },
    ],
    profileUrl: "https://github.com/meera",
    contributionScore: 48,
    tags: ["blockchain", "web3", "solidity"],
    notes: "DeFi protocol developer and Web3 tools creator.",
  },
  {
    username: "sureshp",
    avatar: "https://avatars.githubusercontent.com/u/123456",
    bio: "iOS developer. Swift and SwiftUI enthusiast.",
    publicRepos: 42,
    followers: 310,
    following: 14,
    totalStars: 620,
    totalForks: 155,
    topLanguages: ["Swift", "Objective-C", "C++"],
    topRepos: [
      { name: "swiftui-components", stars: 380, language: "Swift", url: "https://github.com/sureshp/swiftui-components" },
      { name: "ios-architecture", stars: 220, language: "Swift", url: "https://github.com/sureshp/ios-architecture" },
    ],
    profileUrl: "https://github.com/sureshp",
    contributionScore: 40,
    tags: ["ios", "swift", "mobile"],
    notes: "iOS app architecture and SwiftUI components.",
  },
  {
    username: "laxmiv",
    avatar: "https://avatars.githubusercontent.com/u/234567",
    bio: "Game developer. Unity and Unreal Engine.",
    publicRepos: 37,
    followers: 280,
    following: 22,
    totalStars: 510,
    totalForks: 130,
    topLanguages: ["C#", "C++", "Lua"],
    topRepos: [
      { name: "unity-plugins", stars: 290, language: "C#", url: "https://github.com/laxmiv/unity-plugins" },
      { name: "game-framework", stars: 200, language: "C++", url: "https://github.com/laxmiv/game-framework" },
    ],
    profileUrl: "https://github.com/laxmiv",
    contributionScore: 36,
    tags: ["gamedev", "unity", "unreal"],
    notes: "Game development tools and frameworks.",
  },
  {
    username: "ganeshb",
    avatar: "https://avatars.githubusercontent.com/u/345678",
    bio: "Rust developer. Systems programming and WebAssembly.",
    publicRepos: 31,
    followers: 520,
    following: 10,
    totalStars: 1100,
    totalForks: 280,
    topLanguages: ["Rust", "WebAssembly", "C"],
    topRepos: [
      { name: "rust-web-server", stars: 650, language: "Rust", url: "https://github.com/ganeshb/rust-web-server" },
      { name: "wasm-tools", stars: 420, language: "Rust", url: "https://github.com/ganeshb/wasm-tools" },
    ],
    profileUrl: "https://github.com/ganeshb",
    contributionScore: 58,
    tags: ["rust", "webassembly", "systems"],
    notes: "Rust systems programming and WASM tools.",
  },
  {
    username: "nehaa",
    avatar: "https://avatars.githubusercontent.com/u/456789",
    bio: "Cloud architect. AWS and Azure specialist.",
    publicRepos: 44,
    followers: 390,
    following: 16,
    totalStars: 720,
    totalForks: 185,
    topLanguages: ["Python", "TypeScript", "Shell"],
    topRepos: [
      { name: "aws-lambda-utils", stars: 420, language: "Python", url: "https://github.com/nehaa/aws-lambda-utils" },
      { name: "azure-templates", stars: 280, language: "TypeScript", url: "https://github.com/nehaa/azure-templates" },
    ],
    profileUrl: "https://github.com/nehaa",
    contributionScore: 46,
    tags: ["cloud", "aws", "azure"],
    notes: "Cloud infrastructure and serverless architectures.",
  },
  {
    username: "amitd",
    avatar: "https://avatars.githubusercontent.com/u/567890",
    bio: "Database engineer. PostgreSQL and MongoDB expert.",
    publicRepos: 39,
    followers: 340,
    following: 13,
    totalStars: 640,
    totalForks: 160,
    topLanguages: ["SQL", "Python", "Go"],
    topRepos: [
      { name: "postgres-extensions", stars: 380, language: "SQL", url: "https://github.com/amitd/postgres-extensions" },
      { name: "mongo-optimizer", stars: 240, language: "Python", url: "https://github.com/amitd/mongo-optimizer" },
    ],
    profileUrl: "https://github.com/amitd",
    contributionScore: 42,
    tags: ["database", "postgresql", "mongodb"],
    notes: "Database optimization and extension development.",
  },
  {
    username: "poojar",
    avatar: "https://avatars.githubusercontent.com/u/678901",
    bio: "UI/UX designer turned developer. CSS and design systems.",
    publicRepos: 36,
    followers: 450,
    following: 28,
    totalStars: 820,
    totalForks: 210,
    topLanguages: ["CSS", "JavaScript", "HTML"],
    topRepos: [
      { name: "design-system", stars: 480, language: "CSS", url: "https://github.com/poojar/design-system" },
      { name: "css-animations", stars: 320, language: "CSS", url: "https://github.com/poojar/css-animations" },
    ],
    profileUrl: "https://github.com/poojar",
    contributionScore: 50,
    tags: ["css", "design-systems", "frontend"],
    notes: "Design systems and CSS animation libraries.",
  },
  {
    username: "rajeshn",
    avatar: "https://avatars.githubusercontent.com/u/789012",
    bio: "Embedded systems developer. IoT and hardware.",
    publicRepos: 34,
    followers: 260,
    following: 11,
    totalStars: 480,
    totalForks: 125,
    topLanguages: ["C", "C++", "Python"],
    topRepos: [
      { name: "iot-platform", stars: 280, language: "C", url: "https://github.com/rajeshn/iot-platform" },
      { name: "embedded-drivers", stars: 190, language: "C++", url: "https://github.com/rajeshn/embedded-drivers" },
    ],
    profileUrl: "https://github.com/rajeshn",
    contributionScore: 34,
    tags: ["embedded", "iot", "hardware"],
    notes: "IoT platforms and embedded systems development.",
  },
  {
    username: "divyag",
    avatar: "https://avatars.githubusercontent.com/u/890123",
    bio: "AI/ML researcher. Deep learning and computer vision.",
    publicRepos: 41,
    followers: 620,
    following: 19,
    totalStars: 1350,
    totalForks: 340,
    topLanguages: ["Python", "C++", "CUDA"],
    topRepos: [
      { name: "deep-vision", stars: 780, language: "Python", url: "https://github.com/divyag/deep-vision" },
      { name: "neural-nets", stars: 520, language: "Python", url: "https://github.com/divyag/neural-nets" },
    ],
    profileUrl: "https://github.com/divyag",
    contributionScore: 65,
    tags: ["ai", "deep-learning", "computer-vision"],
    notes: "Computer vision and deep learning research.",
  },
  {
    username: "sanjaym",
    avatar: "https://avatars.githubusercontent.com/u/901234",
    bio: "API developer. REST and GraphQL specialist.",
    publicRepos: 47,
    followers: 310,
    following: 17,
    totalStars: 590,
    totalForks: 150,
    topLanguages: ["JavaScript", "TypeScript", "Go"],
    topRepos: [
      { name: "graphql-server", stars: 340, language: "TypeScript", url: "https://github.com/sanjaym/graphql-server" },
      { name: "rest-api-framework", stars: 230, language: "JavaScript", url: "https://github.com/sanjaym/rest-api-framework" },
    ],
    profileUrl: "https://github.com/sanjaym",
    contributionScore: 40,
    tags: ["api", "graphql", "rest"],
    notes: "API design and GraphQL server frameworks.",
  },
  {
    username: "kiranp",
    avatar: "https://avatars.githubusercontent.com/u/1234567",
    bio: "Test automation engineer. Selenium and Cypress.",
    publicRepos: 38,
    followers: 240,
    following: 15,
    totalStars: 420,
    totalForks: 110,
    topLanguages: ["JavaScript", "Python", "Java"],
    topRepos: [
      { name: "test-framework", stars: 240, language: "JavaScript", url: "https://github.com/kiranp/test-framework" },
      { name: "automation-utils", stars: 170, language: "Python", url: "https://github.com/kiranp/automation-utils" },
    ],
    profileUrl: "https://github.com/kiranp",
    contributionScore: 32,
    tags: ["testing", "automation", "qa"],
    notes: "Test automation frameworks and utilities.",
  },
  {
    username: "swatir",
    avatar: "https://avatars.githubusercontent.com/u/2345678",
    bio: "Technical writer and developer advocate.",
    publicRepos: 52,
    followers: 380,
    following: 35,
    totalStars: 680,
    totalForks: 175,
    topLanguages: ["Markdown", "JavaScript", "Python"],
    topRepos: [
      { name: "dev-docs", stars: 380, language: "Markdown", url: "https://github.com/swatir/dev-docs" },
      { name: "api-examples", stars: 280, language: "JavaScript", url: "https://github.com/swatir/api-examples" },
    ],
    profileUrl: "https://github.com/swatir",
    contributionScore: 44,
    tags: ["documentation", "developer-advocacy", "writing"],
    notes: "Developer documentation and API examples.",
  },
  {
    username: "manishk",
    avatar: "https://avatars.githubusercontent.com/u/3456789",
    bio: "Performance engineer. Optimization and profiling.",
    publicRepos: 33,
    followers: 290,
    following: 12,
    totalStars: 540,
    totalForks: 140,
    topLanguages: ["C++", "Rust", "Python"],
    topRepos: [
      { name: "profiler-tool", stars: 320, language: "C++", url: "https://github.com/manishk/profiler-tool" },
      { name: "optimization-guide", stars: 210, language: "Markdown", url: "https://github.com/manishk/optimization-guide" },
    ],
    profileUrl: "https://github.com/manishk",
    contributionScore: 38,
    tags: ["performance", "optimization", "profiling"],
    notes: "Performance profiling tools and optimization guides.",
  },
  {
    username: "ritikaj",
    avatar: "https://avatars.githubusercontent.com/u/4567890",
    bio: "AR/VR developer. Unity and WebXR.",
    publicRepos: 29,
    followers: 350,
    following: 20,
    totalStars: 620,
    totalForks: 160,
    topLanguages: ["C#", "JavaScript", "GLSL"],
    topRepos: [
      { name: "webxr-framework", stars: 380, language: "JavaScript", url: "https://github.com/ritikaj/webxr-framework" },
      { name: "ar-components", stars: 220, language: "C#", url: "https://github.com/ritikaj/ar-components" },
    ],
    profileUrl: "https://github.com/ritikaj",
    contributionScore: 46,
    tags: ["ar", "vr", "webxr"],
    notes: "AR/VR development frameworks and components.",
  },
  {
    username: "ajayv",
    avatar: "https://avatars.githubusercontent.com/u/5678901",
    bio: "Microservices architect. Docker and Kubernetes.",
    publicRepos: 46,
    followers: 410,
    following: 14,
    totalStars: 780,
    totalForks: 200,
    topLanguages: ["Go", "Python", "Shell"],
    topRepos: [
      { name: "microservice-patterns", stars: 450, language: "Go", url: "https://github.com/ajayv/microservice-patterns" },
      { name: "k8s-operators", stars: 310, language: "Go", url: "https://github.com/ajayv/k8s-operators" },
    ],
    profileUrl: "https://github.com/ajayv",
    contributionScore: 50,
    tags: ["microservices", "kubernetes", "docker"],
    notes: "Microservices patterns and Kubernetes operators.",
  },
  {
    username: "nandini",
    avatar: "https://avatars.githubusercontent.com/u/6789012",
    bio: "Natural language processing researcher.",
    publicRepos: 35,
    followers: 480,
    following: 18,
    totalStars: 920,
    totalForks: 240,
    topLanguages: ["Python", "Jupyter Notebook", "C++"],
    topRepos: [
      { name: "nlp-toolkit", stars: 540, language: "Python", url: "https://github.com/nandini/nlp-toolkit" },
      { name: "text-generation", stars: 360, language: "Python", url: "https://github.com/nandini/text-generation" },
    ],
    profileUrl: "https://github.com/nandini",
    contributionScore: 56,
    tags: ["nlp", "machine-learning", "python"],
    notes: "NLP research tools and text generation models.",
  },
  {
    username: "viveks",
    avatar: "https://avatars.githubusercontent.com/u/7890123",
    bio: "Quantum computing researcher.",
    publicRepos: 28,
    followers: 520,
    following: 9,
    totalStars: 1050,
    totalForks: 270,
    topLanguages: ["Python", "Q#", "C++"],
    topRepos: [
      { name: "quantum-algorithms", stars: 620, language: "Python", url: "https://github.com/viveks/quantum-algorithms" },
      { name: "qiskit-examples", stars: 410, language: "Python", url: "https://github.com/viveks/qiskit-examples" },
    ],
    profileUrl: "https://github.com/viveks",
    contributionScore: 60,
    tags: ["quantum", "research", "physics"],
    notes: "Quantum computing algorithms and research.",
  },
  {
    username: "geetam",
    avatar: "https://avatars.githubusercontent.com/u/8901234",
    bio: "E-commerce platform developer.",
    publicRepos: 43,
    followers: 270,
    following: 16,
    totalStars: 490,
    totalForks: 125,
    topLanguages: ["PHP", "JavaScript", "MySQL"],
    topRepos: [
      { name: "ecommerce-platform", stars: 280, language: "PHP", url: "https://github.com/geetam/ecommerce-platform" },
      { name: "payment-gateway", stars: 195, language: "JavaScript", url: "https://github.com/geetam/payment-gateway" },
    ],
    profileUrl: "https://github.com/geetam",
    contributionScore: 35,
    tags: ["ecommerce", "php", "payments"],
    notes: "E-commerce platforms and payment integrations.",
  },
  {
    username: "harishp",
    avatar: "https://avatars.githubusercontent.com/u/9012345",
    bio: "Robotics engineer. ROS and computer vision.",
    publicRepos: 32,
    followers: 380,
    following: 13,
    totalStars: 680,
    totalForks: 175,
    topLanguages: ["C++", "Python", "MATLAB"],
    topRepos: [
      { name: "ros-navigation", stars: 400, language: "C++", url: "https://github.com/harishp/ros-navigation" },
      { name: "robot-vision", stars: 260, language: "Python", url: "https://github.com/harishp/robot-vision" },
    ],
    profileUrl: "https://github.com/harishp",
    contributionScore: 48,
    tags: ["robotics", "ros", "computer-vision"],
    notes: "Robotics navigation and vision systems.",
  },
  {
    username: "shreya",
    avatar: "https://avatars.githubusercontent.com/u/123456",
    bio: "Backend developer. Python and Django.",
    publicRepos: 40,
    followers: 320,
    following: 21,
    totalStars: 580,
    totalForks: 150,
    topLanguages: ["Python", "JavaScript", "HTML"],
    topRepos: [
      { name: "django-rest-api", stars: 340, language: "Python", url: "https://github.com/shreya/django-rest-api" },
      { name: "web-scraper", stars: 220, language: "Python", url: "https://github.com/shreya/web-scraper" },
    ],
    profileUrl: "https://github.com/shreya",
    contributionScore: 42,
    tags: ["python", "django", "backend"],
    notes: "Django REST APIs and web scraping tools.",
  },
  {
    username: "rohitb",
    avatar: "https://avatars.githubusercontent.com/u/234567",
    bio: "Data engineer. Big data and ETL pipelines.",
    publicRepos: 37,
    followers: 290,
    following: 14,
    totalStars: 520,
    totalForks: 135,
    topLanguages: ["Python", "Scala", "Java"],
    topRepos: [
      { name: "spark-pipelines", stars: 300, language: "Scala", url: "https://github.com/rohitb/spark-pipelines" },
      { name: "etl-framework", stars: 210, language: "Python", url: "https://github.com/rohitb/etl-framework" },
    ],
    profileUrl: "https://github.com/rohitb",
    contributionScore: 38,
    tags: ["data-engineering", "spark", "etl"],
    notes: "Big data pipelines and ETL frameworks.",
  },
  {
    username: "anjali",
    avatar: "https://avatars.githubusercontent.com/u/345678",
    bio: "Frontend architect. React and performance optimization.",
    publicRepos: 45,
    followers: 460,
    following: 24,
    totalStars: 840,
    totalForks: 215,
    topLanguages: ["JavaScript", "TypeScript", "CSS"],
    topRepos: [
      { name: "react-performance", stars: 480, language: "TypeScript", url: "https://github.com/anjali/react-performance" },
      { name: "frontend-toolkit", stars: 340, language: "JavaScript", url: "https://github.com/anjali/frontend-toolkit" },
    ],
    profileUrl: "https://github.com/anjali",
    contributionScore: 52,
    tags: ["react", "frontend", "performance"],
    notes: "React performance optimization and frontend tooling.",
  },
  {
    username: "sachint",
    avatar: "https://avatars.githubusercontent.com/u/456789",
    bio: "DevSecOps engineer. Security automation.",
    publicRepos: 34,
    followers: 340,
    following: 11,
    totalStars: 610,
    totalForks: 160,
    topLanguages: ["Python", "Go", "Shell"],
    topRepos: [
      { name: "security-automation", stars: 360, language: "Python", url: "https://github.com/sachint/security-automation" },
      { name: "ci-security", stars: 240, language: "Go", url: "https://github.com/sachint/ci-security" },
    ],
    profileUrl: "https://github.com/sachint",
    contributionScore: 44,
    tags: ["devsecops", "security", "automation"],
    notes: "Security automation and CI/CD security tools.",
  },
  {
    username: "pooja",
    avatar: "https://avatars.githubusercontent.com/u/567890",
    bio: "Full-stack developer. MERN stack specialist.",
    publicRepos: 48,
    followers: 350,
    following: 19,
    totalStars: 650,
    totalForks: 170,
    topLanguages: ["JavaScript", "TypeScript", "MongoDB"],
    topRepos: [
      { name: "mern-starter", stars: 380, language: "JavaScript", url: "https://github.com/pooja/mern-starter" },
      { name: "fullstack-template", stars: 250, language: "TypeScript", url: "https://github.com/pooja/fullstack-template" },
    ],
    profileUrl: "https://github.com/pooja",
    contributionScore: 46,
    tags: ["fullstack", "mern", "javascript"],
    notes: "MERN stack boilerplates and templates.",
  },
  {
    username: "vikass",
    avatar: "https://avatars.githubusercontent.com/u/678901",
    bio: "Blockchain developer. Ethereum and DeFi.",
    publicRepos: 31,
    followers: 420,
    following: 15,
    totalStars: 780,
    totalForks: 200,
    topLanguages: ["Solidity", "JavaScript", "Rust"],
    topRepos: [
      { name: "smart-contracts", stars: 450, language: "Solidity", url: "https://github.com/vikass/smart-contracts" },
      { name: "defi-protocols", stars: 310, language: "Solidity", url: "https://github.com/vikass/defi-protocols" },
    ],
    profileUrl: "https://github.com/vikass",
    contributionScore: 50,
    tags: ["blockchain", "ethereum", "defi"],
    notes: "Smart contracts and DeFi protocol development.",
  },
  {
    username: "meena",
    avatar: "https://avatars.githubusercontent.com/u/789012",
    bio: "iOS developer. Swift and CoreML.",
    publicRepos: 36,
    followers: 310,
    following: 17,
    totalStars: 560,
    totalForks: 145,
    topLanguages: ["Swift", "Objective-C", "Python"],
    topRepos: [
      { name: "coreml-models", stars: 320, language: "Swift", url: "https://github.com/meena/coreml-models" },
      { name: "ios-ml-kit", stars: 220, language: "Swift", url: "https://github.com/meena/ios-ml-kit" },
    ],
    profileUrl: "https://github.com/meena",
    contributionScore: 40,
    tags: ["ios", "swift", "coreml"],
    notes: "CoreML models and iOS machine learning.",
  },
  {
    username: "rameshk",
    avatar: "https://avatars.githubusercontent.com/u/890123",
    bio: "Systems programmer. Linux kernel and drivers.",
    publicRepos: 29,
    followers: 480,
    following: 8,
    totalStars: 920,
    totalForks: 240,
    topLanguages: ["C", "Assembly", "Shell"],
    topRepos: [
      { name: "kernel-modules", stars: 540, language: "C", url: "https://github.com/rameshk/kernel-modules" },
      { name: "device-drivers", stars: 360, language: "C", url: "https://github.com/rameshk/device-drivers" },
    ],
    profileUrl: "https://github.com/rameshk",
    contributionScore: 58,
    tags: ["linux", "kernel", "systems"],
    notes: "Linux kernel modules and device drivers.",
  },
  {
    username: "lavanyam",
    avatar: "https://avatars.githubusercontent.com/u/901234",
    bio: "Product engineer. Startup CTO and mentor.",
    publicRepos: 51,
    followers: 520,
    following: 32,
    totalStars: 980,
    totalForks: 250,
    topLanguages: ["JavaScript", "Python", "Ruby"],
    topRepos: [
      { name: "startup-boilerplate", stars: 560, language: "JavaScript", url: "https://github.com/lavanyam/startup-boilerplate" },
      { name: "mentorship-tools", stars: 400, language: "Python", url: "https://github.com/lavanyam/mentorship-tools" },
    ],
    profileUrl: "https://github.com/lavanyam",
    contributionScore: 60,
    tags: ["startup", "mentorship", "product"],
    notes: "Startup boilerplates and mentorship tools.",
  },
  {
    username: "ashokv",
    avatar: "https://avatars.githubusercontent.com/u/1234567",
    bio: "Network engineer. SDN and network automation.",
    publicRepos: 33,
    followers: 260,
    following: 12,
    totalStars: 470,
    totalForks: 120,
    topLanguages: ["Python", "Go", "YANG"],
    topRepos: [
      { name: "sdn-controller", stars: 270, language: "Python", url: "https://github.com/ashokv/sdn-controller" },
      { name: "network-automation", stars: 190, language: "Go", url: "https://github.com/ashokv/network-automation" },
    ],
    profileUrl: "https://github.com/ashokv",
    contributionScore: 34,
    tags: ["networking", "sdn", "automation"],
    notes: "SDN controllers and network automation tools.",
  },
  {
    username: "kavyas",
    avatar: "https://avatars.githubusercontent.com/u/2345678",
    bio: "Bioinformatics researcher. Genomics and data analysis.",
    publicRepos: 38,
    followers: 440,
    following: 16,
    totalStars: 820,
    totalForks: 210,
    topLanguages: ["Python", "R", "Perl"],
    topRepos: [
      { name: "genomics-toolkit", stars: 480, language: "Python", url: "https://github.com/kavyas/genomics-toolkit" },
      { name: "sequence-analysis", stars: 320, language: "R", url: "https://github.com/kavyas/sequence-analysis" },
    ],
    profileUrl: "https://github.com/kavyas",
    contributionScore: 52,
    tags: ["bioinformatics", "genomics", "research"],
    notes: "Genomics analysis tools and bioinformatics pipelines.",
  },
  {
    username: "manojr",
    avatar: "https://avatars.githubusercontent.com/u/3456789",
    bio: "Game AI developer. Pathfinding and behavior trees.",
    publicRepos: 30,
    followers: 320,
    following: 14,
    totalStars: 580,
    totalForks: 150,
    topLanguages: ["C++", "C#", "Python"],
    topRepos: [
      { name: "pathfinding-lib", stars: 340, language: "C++", url: "https://github.com/manojr/pathfinding-lib" },
      { name: "behavior-trees", stars: 220, language: "C#", url: "https://github.com/manojr/behavior-trees" },
    ],
    profileUrl: "https://github.com/manojr",
    contributionScore: 42,
    tags: ["game-ai", "pathfinding", "algorithms"],
    notes: "Game AI algorithms and behavior tree frameworks.",
  },
  {
    username: "deepalij",
    avatar: "https://avatars.githubusercontent.com/u/4567890",
    bio: "Accessibility engineer. WCAG and inclusive design.",
    publicRepos: 35,
    followers: 380,
    following: 22,
    totalStars: 690,
    totalForks: 180,
    topLanguages: ["JavaScript", "HTML", "CSS"],
    topRepos: [
      { name: "a11y-checker", stars: 400, language: "JavaScript", url: "https://github.com/deepalij/a11y-checker" },
      { name: "inclusive-components", stars: 270, language: "HTML", url: "https://github.com/deepalij/inclusive-components" },
    ],
    profileUrl: "https://github.com/deepalij",
    contributionScore: 48,
    tags: ["accessibility", "a11y", "inclusive-design"],
    notes: "Accessibility testing tools and inclusive component libraries.",
  },
  {
    username: "sureshr",
    avatar: "https://avatars.githubusercontent.com/u/5678901",
    bio: "Compiler engineer. Language design and optimization.",
    publicRepos: 27,
    followers: 460,
    following: 7,
    totalStars: 880,
    totalForks: 225,
    topLanguages: ["C++", "Rust", "LLVM"],
    topRepos: [
      { name: "compiler-frontend", stars: 520, language: "C++", url: "https://github.com/sureshr/compiler-frontend" },
      { name: "optimization-passes", stars: 340, language: "Rust", url: "https://github.com/sureshr/optimization-passes" },
    ],
    profileUrl: "https://github.com/sureshr",
    contributionScore: 56,
    tags: ["compilers", "llvm", "language-design"],
    notes: "Compiler frontends and optimization passes.",
  },
  {
    username: "ramyav",
    avatar: "https://avatars.githubusercontent.com/u/6789012",
    bio: "Search engineer. Elasticsearch and information retrieval.",
    publicRepos: 34,
    followers: 290,
    following: 15,
    totalStars: 530,
    totalForks: 140,
    topLanguages: ["Java", "Python", "Go"],
    topRepos: [
      { name: "search-engine", stars: 310, language: "Java", url: "https://github.com/ramyav/search-engine" },
      { name: "elasticsearch-plugins", stars: 210, language: "Java", url: "https://github.com/ramyav/elasticsearch-plugins" },
    ],
    profileUrl: "https://github.com/ramyav",
    contributionScore: 38,
    tags: ["search", "elasticsearch", "ir"],
    notes: "Search engine development and Elasticsearch plugins.",
  },
  {
    username: "karthikn",
    avatar: "https://avatars.githubusercontent.com/u/7890123",
    bio: "Video processing engineer. FFmpeg and streaming.",
    publicRepos: 31,
    followers: 340,
    following: 13,
    totalStars: 620,
    totalForks: 160,
    topLanguages: ["C", "C++", "Python"],
    topRepos: [
      { name: "video-codec", stars: 360, language: "C", url: "https://github.com/karthikn/video-codec" },
      { name: "streaming-server", stars: 240, language: "C++", url: "https://github.com/karthikn/streaming-server" },
    ],
    profileUrl: "https://github.com/karthikn",
    contributionScore: 44,
    tags: ["video", "streaming", "codec"],
    notes: "Video codec development and streaming servers.",
  },
  {
    username: "bindum",
    avatar: "https://avatars.githubusercontent.com/u/8901234",
    bio: "Cryptographer. Zero-knowledge proofs and cryptography.",
    publicRepos: 26,
    followers: 510,
    following: 9,
    totalStars: 980,
    totalForks: 250,
    topLanguages: ["Rust", "C++", "Python"],
    topRepos: [
      { name: "zkp-library", stars: 580, language: "Rust", url: "https://github.com/bindum/zkp-library" },
      { name: "crypto-primitives", stars: 380, language: "C++", url: "https://github.com/bindum/crypto-primitives" },
    ],
    profileUrl: "https://github.com/bindum",
    contributionScore: 62,
    tags: ["cryptography", "zkp", "security"],
    notes: "Zero-knowledge proof libraries and cryptographic primitives.",
  },
  {
    username: "prakashs",
    avatar: "https://avatars.githubusercontent.com/u/9012345",
    bio: "ERP developer. SAP and enterprise systems.",
    publicRepos: 39,
    followers: 240,
    following: 11,
    totalStars: 410,
    totalForks: 105,
    topLanguages: ["ABAP", "Java", "JavaScript"],
    topRepos: [
      { name: "sap-integration", stars: 230, language: "ABAP", url: "https://github.com/prakashs/sap-integration" },
      { name: "erp-modules", stars: 170, language: "Java", url: "https://github.com/prakashs/erp-modules" },
    ],
    profileUrl: "https://github.com/prakashs",
    contributionScore: 30,
    tags: ["erp", "sap", "enterprise"],
    notes: "SAP integration and ERP module development.",
  },
  {
    username: "snehal",
    avatar: "https://avatars.githubusercontent.com/u/123456",
    bio: "Chatbot developer. Conversational AI and NLP.",
    publicRepos: 36,
    followers: 370,
    following: 18,
    totalStars: 680,
    totalForks: 175,
    topLanguages: ["Python", "JavaScript", "TypeScript"],
    topRepos: [
      { name: "chatbot-framework", stars: 400, language: "Python", url: "https://github.com/snehal/chatbot-framework" },
      { name: "nlp-pipeline", stars: 260, language: "Python", url: "https://github.com/snehal/nlp-pipeline" },
    ],
    profileUrl: "https://github.com/snehal",
    contributionScore: 46,
    tags: ["chatbot", "nlp", "conversational-ai"],
    notes: "Chatbot frameworks and NLP pipelines.",
  },
  {
    username: "vinodk",
    avatar: "https://avatars.githubusercontent.com/u/234567",
    bio: "Graphics programmer. OpenGL and Vulkan.",
    publicRepos: 28,
    followers: 420,
    following: 10,
    totalStars: 760,
    totalForks: 195,
    topLanguages: ["C++", "GLSL", "Rust"],
    topRepos: [
      { name: "vulkan-renderer", stars: 440, language: "C++", url: "https://github.com/vinodk/vulkan-renderer" },
      { name: "opengl-examples", stars: 300, language: "GLSL", url: "https://github.com/vinodk/opengl-examples" },
    ],
    profileUrl: "https://github.com/vinodk",
    contributionScore: 52,
    tags: ["graphics", "vulkan", "opengl"],
    notes: "Graphics rendering engines and shader examples.",
  },
  {
    username: "aishwaryap",
    avatar: "https://avatars.githubusercontent.com/u/345678",
    bio: "Healthcare IT. Medical imaging and DICOM.",
    publicRepos: 32,
    followers: 310,
    following: 14,
    totalStars: 560,
    totalForks: 145,
    topLanguages: ["Python", "C++", "Java"],
    topRepos: [
      { name: "dicom-viewer", stars: 320, language: "Python", url: "https://github.com/aishwaryap/dicom-viewer" },
      { name: "medical-imaging", stars: 220, language: "C++", url: "https://github.com/aishwaryap/medical-imaging" },
    ],
    profileUrl: "https://github.com/aishwaryap",
    contributionScore: 40,
    tags: ["healthcare", "medical-imaging", "dicom"],
    notes: "Medical imaging tools and DICOM viewers.",
  },
  {
    username: "ganeshr",
    avatar: "https://avatars.githubusercontent.com/u/456789",
    bio: "Audio processing. DSP and music information retrieval.",
    publicRepos: 30,
    followers: 360,
    following: 16,
    totalStars: 640,
    totalForks: 165,
    topLanguages: ["C++", "Python", "MATLAB"],
    topRepos: [
      { name: "audio-dsp", stars: 380, language: "C++", url: "https://github.com/ganeshr/audio-dsp" },
      { name: "music-analysis", stars: 240, language: "Python", url: "https://github.com/ganeshr/music-analysis" },
    ],
    profileUrl: "https://github.com/ganeshr",
    contributionScore: 46,
    tags: ["audio", "dsp", "music"],
    notes: "Audio DSP libraries and music analysis tools.",
  },
  {
    username: "ujwalav",
    avatar: "https://avatars.githubusercontent.com/u/567890",
    bio: "FinTech developer. Trading systems and algorithms.",
    publicRepos: 34,
    followers: 440,
    following: 12,
    totalStars: 820,
    totalForks: 210,
    topLanguages: ["Python", "C++", "Rust"],
    topRepos: [
      { name: "trading-engine", stars: 480, language: "C++", url: "https://github.com/ujwalav/trading-engine" },
      { name: "algo-strategies", stars: 320, language: "Python", url: "https://github.com/ujwalav/algo-strategies" },
    ],
    profileUrl: "https://github.com/ujwalav",
    contributionScore: 54,
    tags: ["fintech", "trading", "algorithms"],
    notes: "Trading engines and algorithmic trading strategies.",
  },
  {
    username: "nishantg",
    avatar: "https://avatars.githubusercontent.com/u/678901",
    bio: "Edge computing. IoT and distributed systems.",
    publicRepos: 37,
    followers: 330,
    following: 15,
    totalStars: 590,
    totalForks: 155,
    topLanguages: ["Go", "Rust", "C"],
    topRepos: [
      { name: "edge-runtime", stars: 340, language: "Rust", url: "https://github.com/nishantg/edge-runtime" },
      { name: "iot-gateway", stars: 230, language: "Go", url: "https://github.com/nishantg/iot-gateway" },
    ],
    profileUrl: "https://github.com/nishantg",
    contributionScore: 42,
    tags: ["edge-computing", "iot", "distributed"],
    notes: "Edge computing runtimes and IoT gateways.",
  },
];

module.exports = { data: indianProfiles };